(define (problem hanoi_problem)
(:domain HANOI)
(:objects bleu blanc rouge - object left middle right - tower)

(:init  (smaller bleu blanc)
        (smaller blanc rouge)
        (smaller bleu rouge)
        (ontower rouge left)
    		(on blanc rouge)
    		(on bleu blanc)
        (clear bleu)
    		(clear middle)
    		(clear right)
    		(handempty))

(:goal  (and (ontower rouge right)
        (on blanc rouge)
        (on bleu blanc)))
)
